#!/usr/bin/env python3
"""Build Engine — deterministic platform artifacts; final/ is opt-in only."""

import argparse
import importlib.util
import inspect
import json
import sys
from functools import lru_cache
from pathlib import Path

try:
    import yaml
except ImportError:
    print("PyYAML required: pip install pyyaml")
    sys.exit(1)

ROOT = Path(__file__).resolve().parent.parent

from ir import build_ir

PLATFORMS = {
    "clash-meta": ("clash-meta/config.yaml", "yaml"),
    "clash": ("clash/config.yaml", "yaml"),
    "stash": ("stash/config.yaml", "yaml"),
    "egern": ("egern/config.yaml", "yaml"),
    "loon": ("loon/config.conf", "text"),
    "shadowrocket": ("shadowrocket/config.conf", "text"),
    "sing-box": ("sing-box/config.json", "json"),
}


@lru_cache(maxsize=None)
def load_renderer(platform: str):
    path = ROOT / "platforms" / platform / "adapter" / "render.py"
    if not path.exists():
        raise FileNotFoundError(f"missing renderer: {path}")
    spec = importlib.util.spec_from_file_location(f"{platform.replace('-', '_')}_render", path)
    if spec is None or spec.loader is None:
        raise ImportError(f"cannot load renderer: {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    if not hasattr(module, "render"):
        raise AttributeError(f"renderer missing render(): {path}")
    return module.render


def write_output(root_name: str, platform: str, rel_path: str, kind: str, rendered) -> None:
    root = ROOT / root_name
    out_path = root / rel_path
    out_path.parent.mkdir(parents=True, exist_ok=True)
    if kind == "yaml":
        text = yaml.safe_dump(rendered, allow_unicode=True, sort_keys=False)
    elif kind == "json":
        text = json.dumps(rendered, ensure_ascii=False, indent=2) + "\n"
    else:
        text = rendered if isinstance(rendered, str) else str(rendered)
    out_path.write_text(text, encoding="utf-8")
    print(f"✅ Wrote {out_path}")


def build_root(root_name: str, ir) -> None:
    root = ROOT / root_name
    root.mkdir(parents=True, exist_ok=True)
    for platform, (rel_path, kind) in PLATFORMS.items():
        renderer = load_renderer(platform)
        rendered = renderer(ir, platform=platform) if "platform" in inspect.signature(renderer).parameters else renderer(ir)
        write_output(root_name, platform, rel_path, kind, rendered)


def write_rule_audit_index() -> None:
    from rule_audit import audit, markdown

    index, _, _, _, _ = audit()
    audit_dir = ROOT / "build" / "audit"
    audit_dir.mkdir(parents=True, exist_ok=True)
    (audit_dir / "rule-strategy-index.json").write_text(
        json.dumps(index, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    (audit_dir / "rule-strategy-index.md").write_text(markdown(index), encoding="utf-8")
    print(f"✅ Wrote {audit_dir / 'rule-strategy-index.json'}")
    print(f"✅ Wrote {audit_dir / 'rule-strategy-index.md'}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--include-final",
        action="store_true",
        help="also emit legacy final/ compatibility tree",
    )
    args = parser.parse_args()

    ir = build_ir()
    build_root("build", ir)
    write_rule_audit_index()
    if args.include_final:
        build_root("final", ir)
        (ROOT / "final" / "README.md").write_text(
            "# Legacy Compatibility Output\n\nGenerated by `build.py --include-final`.\n",
            encoding="utf-8",
        )
    else:
        print("ℹ️ final/ skipped (use --include-final)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
